// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyMTkksZ6HBlo8HgrdNexhXuxr1lOn-nA',
    appId: '1:951216595960:web:ea4c7e7fab5bf32b83ac0d',
    messagingSenderId: '951216595960',
    projectId: 'quiz-app-basic',
    authDomain: 'quiz-app-basic.firebaseapp.com',
    storageBucket: 'quiz-app-basic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Alrpgrlybv5nUKjUmGXmg8RXkBEw5LI',
    appId: '1:951216595960:android:ed4c5af8b48d80ce83ac0d',
    messagingSenderId: '951216595960',
    projectId: 'quiz-app-basic',
    storageBucket: 'quiz-app-basic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRGGi3ocOrbuPFfOPd0xdQue7DGjbRE8',
    appId: '1:951216595960:ios:80885d1b1109851483ac0d',
    messagingSenderId: '951216595960',
    projectId: 'quiz-app-basic',
    storageBucket: 'quiz-app-basic.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKRGGi3ocOrbuPFfOPd0xdQue7DGjbRE8',
    appId: '1:951216595960:ios:a4a8529d594f6c8983ac0d',
    messagingSenderId: '951216595960',
    projectId: 'quiz-app-basic',
    storageBucket: 'quiz-app-basic.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
